### ISSUE TITLE
Support for google map searches

### ISSUE THREAD

**Issue by mankoff** [Malabarba/emacs-google-this#16]
* Changelog shows support: https://github.com/Bruce-Connor/emacs-google-this/blob/master/google-this.el#L97
 * Key-bindings indicate support (2x!) https://github.com/Bruce-Connor/emacs-google-this/blob/master/google-this.el#L145 and https://github.com/Bruce-Connor/emacs-google-this/blob/master/google-this.el#L146

But nothing appears implemented, and error message is:

`command-execute: Symbol's function definition is void: google-maps`

**Comment by a13** [comment]
well, it looks like you didn't fix the keybinding :)
