### ISSUE TITLE
google-this has some issues when going through proxy

### ISSUE THREAD

**Issue by lwiechec** [Malabarba/emacs-google-this#19]
Hi,

thanks for `google-this`, I love it. However, during my normal working days, I need to go through a HTTP proxy. Here's the error message that I am getting:

```
Contacting host: myproxy:8088
gnutls.c: [0] (Emacs) fatal error: An unexpected TLS packet was received.
gnutls.el: (err=[-15] An unexpected TLS packet was received.) boot: (:priority NORMAL :hostname myproxy :loglevel 0 :min-prime-bits 256 :trustfiles (/etc/ssl/certs/ca-certificates.crt) :crlfiles nil :keylist nil :verify-flags nil :verify-error nil :callbacks nil)
projectile-project-root: GnuTLS error: #<process myproxy>, -15
```

is there an easy way to fix it?...

cheers,
Łukasz

**Comment by lwiechec** [comment]
I read somewhere that it might have something to do with outdated `libgnutls` and that recompilation of emacs from source with new version should help.

It _does_ help. I still have issues but they seem to be [eww related](http://superuser.com/questions/1019629/emacs-eww-cannot-access-https-sites)

**Comment by Malabarba** [comment]
Glad you've solved it. Indeed, google-this doesn't actually do any networking that could've caused this. It simply builds the url and sends it to your default browser.
