### ISSUE TITLE
Is there a way to merge efforts with the engine-mode package?

### ISSUE THREAD

**Issue by CestDiego** [Malabarba/emacs-google-this#20]
Just thinking that there is a lot of potential for those. https://github.com/hrs/engine-mode

**Comment by Malabarba** [comment]
I'm not sure. I like the robustness of engine-mode, and how it offers an easy way to define search engines.
And I like the versatility that google-this gives me with respect to *what* I'm searching (line, word, symbol, prompt).

It would be nice to join the two, so that you could apply any of the various the commands `google-this` provides to the any of the search-engines in engine-mode. But I don't know how we could do it without making keybinds 1-key-longer for everybody.

**Comment by CestDiego** [comment]
couldn't there be a `default` search engine that uses same keybindings as
google-this. and when `C-u` is the prefix of such keybdinging it asks you
what search engine you want from `engine-mode` and does what is expected?


On Sun, May 1, 2016 at 9:35 PM Artur Malabarba <notifications@github.com>
wrote:

> I'm not sure. I like the robustness of engine-mode, and how it offers an
> easy way to define search engines.
> And I like the versatility that google-this gives me with respect to
> *what* I'm searching (line, word, symbol, prompt).
>
> It would be nice to join the two, so that you could apply any of the
> various the commands google-this provides to the any of the
> search-engines in engine-mode. But I don't know how we could do it without
> making keybinds 1-key-longer for everybody.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Malabarba/emacs-google-this/issues/20#issuecomment-216090458>
>
-- 
Diego Berrocal
http://cestdiego.github.io

**Comment by Malabarba** [comment]
We already use `C-u` for quoting the search. But we could use `C-0` instead for that. And `C-1`, `C-2`, etc, could be used to directly invoke a specific engine.

**Comment by CestDiego** [comment]
I like that

On Sun, May 1, 2016 at 10:04 PM Artur Malabarba <notifications@github.com>
wrote:

> We already use C-u for quoting the search. But we could use C-0 instead
> for that. And C-1, C-2, etc, could be used to directly invoke a specific
> engine.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Malabarba/emacs-google-this/issues/20#issuecomment-216092650>
>
-- 
Diego Berrocal
http://cestdiego.github.io

**Comment by Malabarba** [comment]
Closed for inactivity
