### ISSUE TITLE
Custom function `google-this-browse-url-function` cannot changed with `custom-set-variables`

### ISSUE THREAD

**Issue by ccqpein** [Malabarba/emacs-google-this#24]
Hi, `google-this` is a good tool. But I found a bit problem in `google-this-browse-url-function`. 

I wanna to change the `browse-url` to `eww-browse-url`, then I can open google in eww.

But I cannot found the method to change it. I open `M-x customize`, search, but did not find it. 

I add to `custom-set-variables` in `init.el` this var: `'(google-this-browse-url-function 'eww-browse-url)`, cannot work neither.

I figure it out that add `'(browse-url-browser-function 'eww-browse-url)` to `init.el`, which change the behavior of `browse-url`. 

Could you please make it easy to change in next version? 

Thank you~~

**Comment by Malabarba** [comment]
The variable is there. Just use `M-x customize-variable` or `M-x customize-group RET google-this` and you'll find it. ;-)

**Comment by Malabarba** [comment]
Maybe you just didn't have the latest snapshot. I've now pushed a stable release that contains this variable.

**Comment by ccqpein** [comment]
YES! I update when received your reply by email. Then I find it, you are right. Thank you!
