### ISSUE TITLE
Force localization with w3m ?

### ISSUE THREAD

**Issue by pseudomyne** [Malabarba/emacs-google-this#25]
Hi. Thank you for **google-this**.  Though being french, I like to use the US google domain for some queries. The thing is google brings you back from the US domain to the frogs continent when using the .com suffix. (co.uk works well in w3m and in ffx). 

So we frenchies need to use this suffix to access the US domain :
https://www.google.com/?hl=en&gws_rd=cr#hl=en&q=
Then putting :

```
(defun google-this-url ()
  "URL for google searches."
  (concat google-this-base-url google-this-location-suffix "?hl=en&gws_rd=cr#hl=en&q=%s"))
```

in your code works well... but just with firefox. This does not work in w3m. Would you know why ? Thanks again.

**Comment by Malabarba** [comment]
no idea. =/
Have you verified that w3m is indeed taking you to that exact url?

**Comment by pseudomyne** [comment]
You're right. No, it does not take the right url ; it takes this :
https://www.google.com/?hl=en&gws_rd=cr

though it should take this :
https://www.google.com/?hl=en&gws_rd=cr#hl=en&q=mygooglequery

Adding the message :
No such anchor: hl=en&q=mygooglequery

**Comment by Malabarba** [comment]
THat makes some sense. `#blabla` usually means "Take me to the html element with `id="blabla"`. I'm surprised it works with firefox. =/
