### ISSUE TITLE
How to hide google-this-mode with Diminish?

### ISSUE THREAD

**Issue by ReneFroger** [Malabarba/emacs-google-this#26]
I use the https://github.com/myrjola/diminish.el package.

The strange thingy is that Dminish works well for all modes, but I never managed to hide Google-this-mode in the statusbar.

Examples:

```
(with-eval-after-load 'google-this-mode
(google-this-mode . ""))


(diminish 'google-this-mode)


(with-eval-after-load 'google-this-mode
    (diminish 'google-this-mode))
```

The Google mode is still popping up in my mode line. Another suggestion?

**Comment by Malabarba** [comment]
Might be some technicality about how diminish works. You should be able to customize google-this-modeline-indicator instead.

**Comment by peterwvj** [comment]
This works for me in Emacs 26.0.50.2 (snapshot):

```elisp
(eval-after-load "google-this"
  '(diminish 'google-this-mode))
```
