### ISSUE TITLE
Please specify the license for this packages

### ISSUE THREAD

**Issue by tarsius** [Malabarba/emacs-google-this#28]
Could you please specify the license used by your Emacs packages?

Assuming that you want to release under "the GPL v3 or any later version", the best way to do that would be to add this to the library header:

```
;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

You could also, or instead, add a `LICENSE` file containing the [text of the GPL-3](https://www.gnu.org/licenses/gpl-3.0.txt). But if you only add that file, then the "or (at your option) any later version" bit won't be known.  I recommend that you do *both*.

If this is too noisy for you, then you could also add one of these following lines to the header.  (I do however recommend against doing *only* that - a judge might decide that this is not sufficient.)

```
;; License: GNU General Public License version 3, or (at your option) any later version
;; License: GNU General Public License version 3, or any later version
;; License: GNU GPL version 3, or (at your option) any later version
;; License: GPL version 3, or (at your option) any later version
;; License: GPL version 3, or any later version
;; License: GPL v3, or (at your option) any later version
;; License: GPL v3, or any later version
;; License: GPL-3+
```

**Comment by tarsius** [comment]
Ping. (I need some progress with the remaining ~90 unlicensed packages to keep Richard from requesting the immediate removal of all unlicensed packages from Melpa. That's something I really would like to avoid because it would cause a lot of bad blood.)

**Comment by Malabarba** [comment]
Sorry for not replying Jonas. I have no problem with adding the license, it's really just a matter of remembering to do it when I'm at work. I'll try to remember to do it tomorrow morning.

**Comment by Malabarba** [comment]
In a separate note. Why would Richard care about what's on Melpa? Is this part of an effort to have emacs come pre-configured for Melpa or something like that? (sorry, I haven't followed any discussions lately).

**Comment by tarsius** [comment]
> Why would Richard care about what's on Melpa?

He considers it a violation of the GPLv3 and that's something that he cannot let go unfixed. I don't consider it a violation of the GPL because in my opinion something that is not Emacs does not have to comply with Emacs' licensing terms. Saying that all Emacs lisp has to be released under the same terms as Emacs itself to me is like saying that every Python program has to be released under the same terms as Python itself.
